apiVersion: v1
kind: Secret
metadata:
  labels:
    app: mongodb-replicaset
  name: mongodb-replicaset-keyfile
  namespace: hero-flow
type: Opaque
data:
  key.txt: NVNnZDlyYUlQWHJLSlhmOEc3MGNpb0NsVzZ1dWw4VW1TU3NiNHc2dQ==
