apiVersion: v1
kind: Secret
metadata:
  labels:
    app: mongodb-replicaset
    chart: mongodb-replicaset-3.9.6
    heritage: Tiller
    release: release-name
  name: release-name-mongodb-replicaset-keyfile
type: Opaque
data:
  key.txt: NVNnZDlyYUlQWHJLSlhmOEc3MGNpb0NsVzZ1dWw4VW1TU3NiNHc2dQ==
