apiVersion: v1
kind: Secret
metadata:
  labels:
    app: mongodb-replicaset
    chart: mongodb-replicaset-3.9.6
    heritage: Tiller
    release: release-name
  name: release-name-mongodb-replicaset-admin
type: Opaque
data:
  user: ZGJhZG1pbg==
  password: aXdrWEY0V3RHR3VBQi1nY2piSEtMN2s3VkFka0tT
