apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb-replicaset
  name: mongodb-replicaset-client
  namespace: hero-flow
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: mongodb
      port: 27017
  selector:
    app: mongodb-replicaset

