kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: nfs
  labels:
    app: nfs-server-provisioner
provisioner: cluster.local/nfs-server-provisioner
reclaimPolicy: Delete

allowVolumeExpansion: true


mountOptions:
  - vers=4.1
  - noatime
