---
# Source: admin/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: hero-flow-admin
  namespace: hero-flow
  labels:
    app.kubernetes.io/name: admin
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: remoting
      protocol: TCP
      name: 8080
  selector:
    app.kubernetes.io/name: admin
    app: hero-flow-k8

---
# Source: admin/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hero-flow-admin
  namespace: hero-flow
  labels:
    app.kubernetes.io/name: admin
    app: hero-flow-k8
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: admin
      app: hero-flow-k8
  template:
    metadata:
      labels:
        app.kubernetes.io/name: admin
        app: hero-flow-k8
    spec:
      containers:
        - name: admin
          image: "saleshero/sflow-admin:latest"
          imagePullPolicy: Always
          env:
            - name: "JAVA_OPTS"
              value: "-Dconfig.resource=application-kubernetes.conf"
            - name: "sf_storage_folder"
              value: "/opt/sflow"
            - name: "ah_snapshots_root"
              value: "/opt/sflow/snapshots"
            - name: "LOGFOLDER"
              value: "/opt/sflow/logs/admin"
            - name: "MONGODB_USER"
              value: "dbadmin"
            - name: "MONGODB_PASS"
              value: "iwkXF4WtGGuAB-gcjbHKL7k7VAdkKS"
            - name: "MONGODB_NAME"
              value: "db0"
            - name: "MONGODB_HOST"
              value: "mongodb-replicaset-client.heroflow"
            - name: "MONGODB_PORT"
              value: "27017"
            - name: "POD_IP"
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            # akka remoting
            - name: remoting
              containerPort: 2551
              protocol: TCP
            # When
            # akka.management.cluster.bootstrap.contact-point-discovery.port-name
            # is defined, it must correspond to this name:
            - name: management
              containerPort: 8558
              protocol: TCP
          volumeMounts:
            - mountPath: /opt/sflow
              name: ext-dir0
      volumes:
        - name: ext-dir0
          persistentVolumeClaim:
            claimName: app


