kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: app
  namespace: hero-flow
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "nfs"
  resources:
    requests:
      storage: 90Gi
