kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: app
  namespace: heroflow
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "nfs"
  resources:
    requests:
      storage: 99Gi
